### ISSUE TITLE
Kubexit doesn't notice ready birth dependency when ready at startup

### ISSUE THREAD

**Issue by RemcodM** [karlkfi/kubexit#6]
Hi again!

After #3 I found out why the timeout for birth dependencies is reached seemingly randomly for us. It is caused by a race condition between kubexit wachting the birth dependencies and the birth dependency itself getting ready.

When kubexit starts watching the birth dependencies after they have already become ready, kubexit will never continue (until the birth dependency timeout) because it only handles `Modified` events. Such an event is never emitted if the birth dependency was already in the ready state.

I will provide a PR in a few minutes that solves this issue.

**Comment by karlkfi** [comment]
Release v0.3.2 has the fix from #7. Thanks again!
